namespace CustomerManagement.Api.Models;

/// <summary>
/// Represents a customer record stored in the database.
/// </summary>
public class Customer
{
    /// <summary>The unique identifier generated by the database on insert.</summary>
    public int Id { get; set; }

    /// <summary>The customer's first name.</summary>
    public String FirstName { get; set; } = string.Empty;

    /// <summary>The customer's last name.</summary>
    public String LastName { get; set; } = string.Empty;

    /// <summary>The customer's email address.</summary>
    public String Email { get; set; } = string.Empty;
}
